name: Spotify ELT Pipeline

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 8 * * *'  # Executa todo dia às 8h UTC

jobs:
  run-spotify-pipeline:
    runs-on: ubuntu-latest

    steps:
      # clonar o repositório
      - name: Checkout
        uses: actions/checkout@v3

      # configurar o Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # instalação das dependencias principais
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r spotify-extract-data/requirements.txt
          pip install dbt-core dbt-bigquery pandas requests pandas_gbq
        shell: bash

      # extração spotify -> bq
      - name: Extrair dados do Spotify
        run: |
          set -x
          cd spotify-extract-data
          python main.py
        shell: bash
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}

      # transformacao dbt
      - name: Executar DBT Transformations
        run: |
          set -x
          cd spotify-dbt/spotify_project
          # criar arquivo temporário de credenciais
          echo "$GCP_CREDENTIALS_JSON" > /tmp/gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-key.json
          dbt run --profiles-dir .
        shell: bash
        env:
          GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
